all: etap1 etap2 etap3

etap1:
	pandoc etap1.md -o etap1.pdf --from markdown --template eisvogel.tex

etap2:
	pandoc etap2.md -o etap2.pdf --from markdown --template eisvogel.tex

etap3:
	pandoc etap3.md -o etap3.pdf --from markdown --template eisvogel.tex
