all: etap1 etap2 etap3

etap1: etap1.md
	pandoc etap1.md -o etap1.pdf --from markdown --template eisvogel.tex

etap2: etap2.md
	pandoc etap2.md -o etap2.pdf --from markdown --template eisvogel.tex

etap3: etap3.md
	pandoc etap3.md -o etap3.pdf --from markdown --template eisvogel.tex
